# Generated by Django 4.1.4 on 2022-12-30 08:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.TextField()),
                ('answer', models.TextField()),
                ('posted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('correct', models.IntegerField(default=0)),
                ('miss', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Folder1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('body', models.TextField()),
                ('posted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('like', models.IntegerField(default=0)),
            ],
        ),
    ]
